### ISSUE TITLE
TFAR force spectator für Replay

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_OnTheFly.Stratis#100]

**Comment by nomisum** [comment]
replay update sollte auch helfen.

**Comment by McDiod** [comment]
Relativ sicher, dass ich die Module aktualisiert hab. Ist die neueste Version npm released?

**Comment by nomisum** [comment]
grad replay ist umgezogen in 
```
node_modules\@gruppe-adler\replay\
```
und entsprechend released

Eine Entscheidung, die ich maximal bereue. Aber ist jetzt leider so. Grund war ein Versuch, grad_replay in grad-replay umzubiegen, was npm nicht geschmeckt hat weil zu ähnlich.. den Clusterfuck ausflösen konnte ich dann nur mit der Orga @gruppe-adler
