### ISSUE TITLE
bugs 23.03.

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_OnTheFly.Stratis#106]
- [x] medic system strange - teilweise zuviel ausgehalten/nach mehreren treffern nicht tot, teilweise unheilbar getroffen trotz sofortiger behandlung
- [ ] ~~kein UGL commander~~

**Comment by McDiod** [comment]
Mediczeug hoffentlich mit nächstem grad-tvtsettings update behoben.

**Comment by McDiod** [comment]
> kein UGL commander

Sieht aus als wäre das by design. Keines der grad-factions-tvt squadleader Loadouts hat UGL. Ich glaube weil einige Longranges zu wenig Stauraum für die Granaten haben.
