### ISSUE TITLE
Tourniquet & Bandagen

### ISSUE THREAD

**Issue by AdlerSalbei** [gruppe-adler/TvT_OnTheFly.Stratis#112]
Die Spieler haben zu wenig Bandagen und so ein Tourniquet oder 2 wäre in manchen Situationen sehr Praktisch.

**Comment by McDiod** [comment]
Benutzt jemand Tourniquets im Basic Medical? Zwei Bandagen rauf ist nicht viel langsamer und dann hat man Ruhe.

**Comment by AdlerSalbei** [comment]
Nicht wenn man 10+ wunden am ganzen Körper hat so wie ich heute 2 mal

**Comment by McDiod** [comment]
https://github.com/gruppe-adler/grad-factions-tvt/commit/05cf062d391bc93a9b234f63524d7b2c02a31399
