### ISSUE TITLE
Idee für BUFOR spawn.

### ISSUE THREAD

**Issue by AdlerXiviD** [gruppe-adler/TvT_OnTheFly.Stratis#23]
Wir hatten ja die Diskussion dass man BLUFOR als Feind erst bemerkt wenn Sie angreifen. Das könnte man insofern lösen, dass wenn BLUFOR den Spawnpunkt auswählt, Sie nicht am Boden spawnen sondern als Faltschirmspringer runter fallen (Evtl das Halo script benutzen). Das würde Opfor zumindest die Chance geben den Feind zu sehen. Und auf die Entfernung von min 2km besteht auch nicht die Gefahr, dass Opfor die Springer abschießt. Das würde auch den Einsatz ein bisschen realistischer wirken lassen. Sozusagen eine Sondereinheit die geschickt wurde um eine Feindzelle zu bekämpfen, blablablub.

**Comment by nomisum** [comment]
Möglicherweise als optionale Möglichkeit für BLUFOR, ohne min.-Reichweite zu spawnen? Oder lassen wirs komplett?
