### ISSUE TITLE
remove mod dependency

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_OnTheFly.Stratis#37]
build fallbacks for vanilla game

**Comment by AdlerXiviD** [comment]
Frage ist: Wollen wir wirklich die map vollkommen ohne Mods machen? 
Ohne AiA und CAF ist die Map relativ sinnlos.

Wenn ja: Was müssen wir machen?
- Alle Module (AGM) löschen
- Loadouts löschen (Da Waffen/Uniform -> Mods)
- Neue Loadouts erstellen? (Oder standardloadouts und sagen man muss VA benutzen)
- VA die whitelist raus? Den Leute die Möglichkeit geben ihre eigenen regeln zu machen?

**Comment by nomisum** [comment]
Ich würd sagen wer Vanilla spielt bekommt Loadouts und VA Vanilla aber ohne Scopes. Unlocked VA wärs ne ganz andere Gameplay Experience. Und ja, befürchte wir müssen die AGM Module löschen. AiA + TFAR  würd ich drinlassen und CAF auch. Glaube wer ACRE nutzt ist son Freak, der kann das notfalls auch selber editieren.

**Comment by AdlerXiviD** [comment]
Also dependencies sind: AiA, CAF und TFAR

**Comment by nomisum** [comment]
- on  hold - first release with all dependencies
