### ISSUE TITLE
buglist 26.01.2014

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_OnTheFly.Stratis#51]
- [x] Kiste BLUFOR spawned nicht
- [x] Capraia EndSpawn im Wasser
- [x] OPFOR-Transporter spawned bei BLUFOR
- [x] Arsenal klappt nicht (keine Aktion?)
- [x] Heli spawned doppelt bei OPFOR UND BLUFOR
- [x] Zielposition wechselt zwischen Initial- und Spawnposition
- [x] Ü bei Gewinnmeldung fehlt
- [x] Ersatz für PKM finden

**Comment by AdlerXiviD** [comment]
![2015-01-26_00002](https://cloud.githubusercontent.com/assets/9570445/5909208/aaa81558-a5ae-11e4-89e7-a614784aed6b.jpg)

**Comment by Fusselwurm** [comment]
Capraia... is das nich eh raus jetz?
