### ISSUE TITLE
Kleinigkeiten

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_OnTheFly.Stratis#71]
- Blufor Tracking anschalten?
- Ende wird für Spectator nicht getriggered bzw. Trigger teilweise auf deutsch UND englisch?!
- Vehicle Spawnen in Blickrichtung?

**Comment by AdlerSalbei** [comment]
Ich würde Bluforce Tracking als optional eintragen. Hatten wir das nicht mal an? Errinere mich wage an ihrgend welche Zeus Missionen.

**Comment by Fusselwurm** [comment]
link #82

**Comment by Fusselwurm** [comment]
> Vehicle Spawnen in Blickrichtung?

Im Sinne von "im Sichtfeld" ?
