### ISSUE TITLE
ACRE2 compatibility

### ISSUE THREAD

**Issue by Fusselwurm** [gruppe-adler/TvT_OnTheFly.Stratis#85]
prepare for ACRE2 - whatever is necessary (frequency/channel settings, distribute radios etc)

**Comment by nomisum** [comment]
war das nicht für BC gedacht und nicht OTF?

2015-10-28 14:14 GMT+01:00 Moritz Schmidt <notifications@github.com>:

**Comment by Fusselwurm** [comment]
warum nich beides? wird ja ähnlich sein. ticket für BC mach ich auch gleich auf :)

**Comment by nomisum** [comment]
lol OK. ja, ist ähnlich. OTF wird aber nicht so schnell
GA_Mod-unabhängig/Eventtauglich.

2015-10-28 14:16 GMT+01:00 Moritz Schmidt <notifications@github.com>:
